---
- name: Install and Configure necessary dependencies
  hosts: tag_Ansible_Slave
  user: ec2-user
  become: yes
  become_method: sudo

  roles:
  - common

- name: Install and Configure apache httpd Server
  hosts: tag_Ansible_Slave
  user: ec2-user
  become: yes
  become_method: sudo

  roles:
  - apache
